[phases.setup]
cmds = [
    'apt-get update',
    'apt-get install -y libicu-dev',
    'docker-php-ext-install intl pdo pdo_mysql'
]

[phases.install]
cmds = ['composer install --optimize-autoloader --no-scripts --no-interaction --no-dev']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'
